pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git branch:  'main',  url:'https://github.com/sandeep-1511/Arcitech.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                #!/bin/bash
                cd ${WORKSPACE}
                python3 -m venv venv
                . venv/bin/activate
                pip install flask gunicorn
                '''
            }
        }
        stage('Run Tests') {
            steps {
                sh '''
                #!/bin/bash
                . ${WORKSPACE}/venv/bin/activate
                # Add test commands here, for example:
                # python -m unittest discover
                echo "Running tests..."
                '''
            }
        }
    }
}
